# Generated by Django 5.0.4 on 2024-05-03 17:35

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
