# Generated by Django 5.0.4 on 2024-05-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sliderimage_image_alter_sliderimage_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ['order'], 'verbose_name': 'Изображение для слайдера', 'verbose_name_plural': 'Изображения для слайдера'},
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
